# Tile Configuration for 2D Minecraft-like World
# Defines visual properties for all tile types in the game

[stone]
name = "Stone"
character = "█"
font_color = [128, 128, 128]  # Gray (not used in seamless mode)
background_color = [128, 128, 128]  # Gray - this fills the entire cell seamlessly

[dirt]
name = "Dirt"
character = "▓"
font_color = [139, 69, 19]  # Saddle brown (not used in seamless mode)
background_color = [101, 67, 33]  # Dark brown - this fills the entire cell

[grass]
name = "Grass"
character = "▒"
font_color = [34, 139, 34]  # Forest green (not used in seamless mode)
background_color = [0, 100, 0]  # Dark green - this fills the entire cell

[water]
name = "Water"
character = "~"
font_color = [173, 216, 230]  # Light blue
background_color = [0, 0, 139]  # Dark blue

[sand]
name = "Sand"
character = "░"
font_color = [255, 218, 185]  # Peach puff
background_color = [194, 178, 128]  # Tan

[wood]
name = "Wood"
character = "║"
font_color = [160, 82, 45]  # Saddle brown
background_color = [101, 67, 33]  # Dark brown

[leaves]
name = "Leaves"
character = "♠"
font_color = [50, 205, 50]  # Lime green
background_color = [34, 139, 34]  # Forest green

[coal]
name = "Coal"
character = "●"
font_color = [105, 105, 105]  # Dim gray
background_color = [25, 25, 25]  # Very dark gray

[iron]
name = "Iron"
character = "◆"
font_color = [192, 192, 192]  # Silver
background_color = [128, 128, 128]  # Gray

[gold]
name = "Gold"
character = "◇"
font_color = [255, 215, 0]  # Gold
background_color = [184, 134, 11]  # Dark goldenrod

[void]
name = "Void"
character = " "
font_color = [0, 0, 0]  # Black
background_color = [0, 0, 0]  # Black

[center_marker]
name = "Center Marker"
character = "."
font_color = [255, 255, 0]  # Yellow
background_color = [128, 128, 128]  # Gray
