[application]
title = "Covenant"
version = "0.1.0"

[window]
initial_width = 80
initial_height = 50
vsync = true

[world]
center_x = 0
center_y = 0
radius = 50
generator_type = "pipeline"  # Pipeline-based world generation
seed = 123456  # Random seed for chunk generation
chunk_size = 16  # Fixed size for all chunks (both generation and rendering)

# Infinite world settings
render_distance = 2  # Buffer distance in chunks beyond screen edges (for smooth movement)
chunk_cache_limit = 100  # Maximum number of chunks to keep in memory
chunk_unload_distance = 5  # Unload chunks beyond this distance from screen viewport

# Multi-scale sampling pipeline configuration
# Fixed 16x16 chunks with multi-scale sampling within chunks
pipeline_layers = [
    "continental",
    "regional",
    "local",
    "tiles"
]

[camera]
# Initial camera position (world coordinates)
initial_x = 0
initial_y = 0
# Movement settings
move_speed = 1  # Tiles per key press
fast_move_speed = 5  # Tiles per key press when holding Shift

# Multi-scale sampling layer configurations
[world.continental]
region_size = 4  # 4x4 chunks per continental region (64x64 tiles)
noise_scale = 0.01
continent_threshold = 0.3
land_ratio = 0.3  # 30% of regions should be continental land

[world.regional]
noise_scale = 0.1
land_bias_from_continental = 0.7  # How much continental designation influences regional sampling
coastal_variation = 0.3  # Amount of variation in coastal regions

[world.local]
sampling_resolution = 8  # 8x8 samples within each 16x16 chunk
noise_scale = 0.5
coastal_detail_iterations = 3
erosion_probability = 0.1
expansion_probability = 0.2

[world.tiles]
# Final tile placement rules
default_land_tile = "grass"
default_water_tile = "water"
coastal_tile = "sand"
deep_water_tile = "deep_water"

[debug]
show_debug_on_startup = true
show_coordinates_on_startup = true
show_fps_on_startup = false

[rendering]
seamless_blocks_enabled = true
clear_color = [0, 0, 0]  # Black background

[ui]
# UI panel colors
panel_background = [32, 32, 48]  # Dark blue-gray
border_color = [128, 128, 160]   # Light blue-gray
info_color = [255, 255, 255]     # White
warning_color = [255, 255, 0]    # Yellow
debug_color = [128, 255, 128]    # Light green

# Panel layout
top_panel_max_lines = 2
bottom_panel_max_lines = 3
panel_margin = 2  # Characters from screen edge
