# Game Configuration for Covenant - 2D World Generator

[app]
title = "Covenant - 2D World Generator"
version = "0.1.0"

[window]
width = 80
height = 50
vsync = true
# font_path = "assets/fonts/terminal.png"  # Commented out - using default font

[camera]
initial_x = 0
initial_y = 0
move_speed = 1
fast_move_speed = 5
